import Link from 'next/link'
import Image from 'next/image'
import Head from 'next/head'
import Script from 'next/script'

export default function FirstPost() {
   return (
      <>
        <html>

        <Head>
        <title>One</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous" />
        </Head>
        <Script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"></Script>
        
        <body>

        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <div class="container-fluid">
                <a class="navbar-brand" href="#">Navbar</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav">
                    <li class="nav-item">
                    <Link href="/"><a class="nav-link" aria-current="page">Home</a></Link>
                    </li>
                    <li class="nav-item">
                    <Link href="/one"><a class="nav-link active" aria-current="page">One</a></Link>
                    </li>
                    <li class="nav-item">
                    <Link href="/two"><a class="nav-link" aria-current="page">Two</a></Link>
                    </li>
                    <li class="nav-item">
                    <Link href="/three"><a class="nav-link" aria-current="page">Three</a></Link>
                    </li>
                    <li class="nav-item">
                    <Link href="/casinos/casumo"><a class="nav-link" aria-current="page">Casumo</a></Link>
                    </li>
                    <li class="nav-item">
                    <Link href="/go/ss" target="_blank"><a class="nav-link" aria-current="page">SS</a></Link>
                    </li>
                </ul>
                </div>
            </div>
        </nav>

        <Image
                src="https://ik.imagekit.io/reltify/tr:w-1600,h-900,q-60,f-auto/504"
                alt="Vercel Logo"
                width={1600}
                height={900}
                priority
              />



        <h1>One</h1>
        <h2>Web Site Main Ingredients:</h2>

        <p>Pages (HTML)</p>
        <p>Style Sheets (CSS)</p>
        <p>Computer Code (JavaScript)</p>
        <p>Live Data (Files and Databases)</p>
        <p>
            <Link href="/two">
               <a>Two</a>
            </Link>
         </p>
         <p>
            <Link href="/">
               <a>Home</a>
            </Link>
         </p>

        </body>
        </html>         
      </>	  
   )
}